name: new_councilmatic
channels:
  - anaconda
  - defaults
dependencies:
  - appnope=0.1.0=py36hf537a9a_0
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - decorator=4.3.0=py36_0
  - intel-openmp=2019.0=118
  - ipykernel=4.9.0=py36_1
  - ipython=6.5.0=py36_0
  - ipython_genutils=0.2.0=py36h241746c_0
  - jedi=0.12.1=py36_0
  - jupyter_client=5.2.3=py36_0
  - jupyter_core=4.4.0=py36_0
  - libcxx=4.0.1=h579ed51_0
  - libcxxabi=4.0.1=hebd6815_0
  - libedit=3.1.20170329=hb402a30_2
  - libffi=3.2.1=h475c297_4
  - libgfortran=3.0.1=h93005f0_2
  - libsodium=1.0.16=h3efe00b_0
  - mkl=2019.0=118
  - mkl_fft=1.0.4=py36h5d10147_1
  - mkl_random=1.0.1=py36h5d10147_1
  - ncurses=6.1=h0a44026_0
  - numpy=1.15.1=py36h6a91979_0
  - numpy-base=1.15.1=py36h8a80b8c_0
  - pandas=0.23.4=py36h6440ff4_0
  - parso=0.3.1=py36_0
  - pexpect=4.6.0=py36_0
  - pickleshare=0.7.4=py36hf512f8e_0
  - pip=10.0.1=py36_0
  - prompt_toolkit=1.0.15=py36haeda067_0
  - ptyprocess=0.6.0=py36_0
  - pygments=2.2.0=py36h240cd3f_0
  - python=3.6.6=hc167b69_0
  - python-dateutil=2.7.3=py36_0
  - pytz=2018.5=py36_0
  - pyzmq=17.1.2=py36h1de35cc_0
  - readline=7.0=h1de35cc_5
  - setuptools=40.2.0=py36_0
  - simplegeneric=0.8.1=py36_2
  - six=1.11.0=py36_1
  - sqlite=3.24.0=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - tornado=5.1=py36h1de35cc_0
  - traitlets=4.3.2=py36h65bd3ce_0
  - wcwidth=0.1.7=py36h8c6ec74_0
  - wheel=0.31.1=py36_0
  - xz=5.2.4=h1de35cc_4
  - zeromq=4.2.5=h0a44026_1
  - zlib=1.2.11=hf3cbc9b_2
  - ca-certificates=2018.03.07=0
  - certifi=2018.8.24=py36_1
  - jinja2=2.10=py36_0
  - markupsafe=1.1.0=py36h1de35cc_0
  - openssl=1.0.2p=h1de35cc_0
  - pip:
    - arrow==0.12.1
    - aws-sam-translator==1.6.0
    - binaryornot==0.4.4
    - boto3==1.9.96
    - botocore==1.12.96
    - chardet==3.0.4
    - click==7.0
    - cookiecutter==1.6.0
    - cython==0.29.5
    - docker==3.4.1
    - docker-pycreds==0.3.0
    - docutils==0.14
    - enum34==1.1.6
    - flask==1.0.2
    - future==0.16.0
    - idna==2.7
    - itsdangerous==1.1.0
    - jinja2-time==0.2.0
    - jmespath==0.9.3
    - jsonschema==2.6.0
    - poyo==0.4.1
    - requests==2.19.1
    - s3transfer==0.2.0
    - selenium==3.14.0
    - tzlocal==1.5.1
    - urllib3==1.23
    - websocket-client==0.48.0
    - werkzeug==0.14.1
    - whichcraft==0.4.1
prefix: /usr/local/anaconda3/envs/new_councilmatic

